services:
  # Database per CatalogService
  catalog-db:
    image: mysql:8.0
    container_name: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: catalogDb
    ports:
      - "3306:3306" # Mappato su localhost per permetterti di connetterti da Rider
    volumes:
      - catalog-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  catalog-db-data: